sync:
  overflow: 0 # overflow sync counter at value or do not set it (0, default)
  interval_ms: 10
heartbeat: # simple heartbeat producer, optional!
  rate: 20 # heartbeat rate
  msg: "77f#05" # message to send, cansend format: heartbeat of node 127 with status 5=Started
defaults: # optional, all defaults can be overwritten per node
  eds_pkg: erl_schunk_pg70 # optional package  name for relative path
  eds_file: "config/Schunk_0_63.dcf" # path to EDS/DCF file
  pos_to_device: "pos*2000000.0"
  pos_from_device: "obj6064/2000000.0"
  vel_to_device: "vel*2000000.0"
  vel_from_device: "obj606C/2000000.0"
nodes:
  motor:
    joint: pg70_finger_left_joint
    id: 12

